# DATA LOADING & UNDERSTANDING (Pandas Basics)

In [23]:
import numpy as np
import pandas as pd

df = pd.read_csv("D:\Ds & Gen Ai\Global Air Quality Analysis\Data\globalAirQuality.csv")
df2= df

# load first 10 data
df.head(10)

# Display dataset shape, column names, and data types.
print(df.shape)
print(df.columns)
print(df.dtypes)

# Identify numerical and categorical columns in the dataset.
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
print("Numerical Columns:")
print(numerical_cols)

# Check for missing values in each column and report their count.
print(df.isnull().sum())

# Generate summary statistics (mean, median, std, min, max) for numerical columns.
print(df.describe())

# Rename columns to follow snake_case naming convention.
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('-', '_')
df.columns

# Convert date/time related columns (if any) to proper datetime format.
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['timestamp']

df

(18000, 15)
Index(['timestamp', 'country', 'city', 'latitude', 'longitude', 'pm25', 'pm10',
       'no2', 'so2', 'o3', 'co', 'aqi', 'temperature', 'humidity',
       'wind_speed'],
      dtype='object')
timestamp       object
country         object
city            object
latitude       float64
longitude      float64
pm25           float64
pm10           float64
no2            float64
so2            float64
o3             float64
co             float64
aqi              int64
temperature    float64
humidity       float64
wind_speed     float64
dtype: object
Numerical Columns:
Index(['latitude', 'longitude', 'pm25', 'pm10', 'no2', 'so2', 'o3', 'co',
       'aqi', 'temperature', 'humidity', 'wind_speed'],
      dtype='object')
timestamp      0
country        0
city           0
latitude       0
longitude      0
pm25           0
pm10           0
no2            0
so2            0
o3             0
co             0
aqi            0
temperature    0
humidity       0
wind_speed     0
dtype: int64
           latitude     longitude          pm25          pm10           no2  \
count  18000.000000  18000.000000  18000.000000  18000.000000  18000.000000
mean      23.065980     37.655560     40.369131     70.152228     32.055176
std       26.156536     78.600701     17.647450     24.999440     13.820680
min      -37.814000   -123.121000      0.025000      0.061000      0.013000
25%       12.972000      2.352000     27.904500     53.125500     22.362500
50%       29.232000     42.146000     40.286500     69.961000     32.019500
75%       41.008000    103.820000     52.436250     87.256500     41.364250
max       60.170000    174.763000    115.683000    161.810000     90.019000

                so2            o3            co           aqi   temperature  \
count  18000.000000  18000.000000  18000.000000  18000.000000  18000.000000
mean       6.035508     48.065100      0.800595    104.645556     21.510251
std        2.454790     14.950849      0.250254     25.616070      9.509444
min        0.003000      0.114000      0.000000     16.000000      5.000000
25%        4.360750     38.028500      0.633000     87.000000     13.357750
50%        6.026000     48.142000      0.800500    103.000000     21.455500
75%        7.715250     58.258500      0.969000    121.000000     29.688250
max       16.559000    103.016000      1.832000    231.000000     37.998000

           humidity    wind_speed
count  18000.000000  18000.000000
mean      57.714351      5.283910
std       18.844908      2.741712
min       25.002000      0.500000
25%       41.320000      2.937000
50%       57.847000      5.297000
75%       74.234750      7.662000
max       89.997000      9.999000

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

# DATA CLEANING & PREPROCESSING (Pandas + NumPy)

In [28]:

import numpy as np
import pandas as pd

df = pd.read_csv("D:\Ds & Gen Ai\Global Air Quality Analysis\Data\globalAirQuality.csv")

# Handle missing values using appropriate techniques (mean/median/mode).
    # numerical columns → fill with median
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

    # categorical columns → fill with mode
cat_cols = df.select_dtypes(include=['object', 'category']).columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# Remove duplicate rows and justify the choice
df.duplicated().copy()

# Detect and handle outliers using IQR or Z-score method (NumPy based)
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1
df = df[~((df[num_cols] < (Q1 - 1.5 * IQR)) | (df[num_cols] > (Q3 + 1.5 * IQR))).any(axis=1)]

# Create a new column categorizing air quality levels (Good, Moderate, Poor).
df['air_quality_level'] = df['aqi'].apply(
    lambda x: 'Good' if x <= 50 else ('Moderate' if x <= 100 else 'Poor'))

# Normalize selected numerical columns using Min-Max normalization.
cols = ['pm25', 'pm10', 'no2', 'so2', 'co', 'o3']
df[cols] = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
df[cols]

# Standardize selected columns using Z-score normalization.
cols = ['pm25', 'pm10', 'no2', 'so2', 'co', 'o3']
df[cols] = (df[cols] - df[cols].mean()) / df[cols].std()
df

# Filter data for a specific country or city using Pandas indexing.
df[df["country"]=='IN']
df[df['city'] == 'Delhi']

# Sort the dataset based on pollution level in descending order.
df_sorted = df.sort_values('aqi', ascending=False)
df_sorted

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed,air_quality_level
8739,2025-11-08 21:25:17.554219,JP,Osaka,34.694,135.502,1.120460,1.834711,2.747202,-0.200943,-0.854959,-1.112631,172,28.127,50.871,6.581,Poor
6787,2025-11-17 13:25:17.554219,IN,Mumbai,19.076,72.878,2.661630,2.494655,0.415141,1.563506,0.885498,-0.556934,172,36.088,59.012,0.630,Poor
6105,2025-11-19 03:25:17.554219,SA,Riyadh,24.714,46.675,2.664460,-0.587484,1.400763,0.587525,2.264658,0.509181,172,16.432,70.913,7.979,Poor
1949,2025-11-10 23:25:17.554219,ES,Madrid,40.417,-3.704,-0.590418,-2.618424,2.730427,-0.202595,0.666781,0.789087,172,18.714,32.971,1.186,Poor
5197,2025-11-11 07:25:17.554219,NG,Lagos,6.524,3.379,2.672255,-0.866835,0.792732,0.477660,-0.070795,1.217180,172,14.734,56.095,0.901,Poor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8942,2025-11-17 08:25:17.554219,JP,Osaka,34.694,135.502,-2.060622,-1.267611,-2.144344,-0.199291,-1.252608,-0.067098,38,8.728,76.028,2.021,Good
11466,2025-11-17 12:25:17.554219,MY,Kuala Lumpur,3.139,101.687,-1.196666,-1.928491,-1.879103,-0.011777,0.396186,0.266321,38,19.672,80.514,0.600,Good
16113,2025-11-16 03:25:17.554219,US,Houston,29.760,-95.370,-1.295984,-2.033639,-1.203529,0.238517,-1.655959,-1.771235,38,8.189,89.883,2.436,Good
10945,2025-11-10 19:25:17.554219,TH,Bangkok,13.756,100.502,-1.226866,-1.554042,-1.723710,-0.591253,0.084774,0.118135,37,17.381,52.137,3.354,Good
15543,2025-11-07 09:25:17.554219,US,Chicago,41.878,-87.630,-1.261858,-2.091666,-1.891905,1.304126,1.592016,-0.470492,36,14.381,55.736,9.747,Good

# DATA ANALYSIS & TRANSFORMATION

In [ ]:
import numpy as np
import pandas as pd

df = df2

# Calculate average pollution levels for each city/country.
    # Average pollution by city
df.groupby('city')['aqi'].mean()
    # Average pollution by country
df.groupby('country')['aqi'].mean()

#  Find top 5 most polluted cities using Pandas groupby.
df.groupby('city')['aqi'].mean().sort_values(ascending=False).head(5)

# Find bottom 5 least polluted cities.
df.groupby('city')['aqi'].mean().sort_values(ascending=False).tail(5)

# Create a pivot table to analyze pollution levels by region and year.
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['year'] = df['timestamp'].dt.year

pivot_table = pd.pivot_table(
    df,
    values='aqi',
    index='country',
    columns='year',
    aggfunc='mean'
)

# Apply conditional filtering to extract “High Risk” pollution zones.
df[df['aqi'] > 200]

# Use .apply() to create a custom pollution severity score.
df['severity_score'] = df['aqi'].apply(lambda x: 'Low' if x <= 50 else 'Moderate' if x <= 100 else 'High' if x <= 200 else 'Severe')
df['severity_score']

# NUMPY-SPECIFIC OPERATIONS

In [ ]:
# Convert Pandas DataFrame columns to NumPy arrays and perform vectorized operations.
pollution = df['aqi'].to_numpy()
adj_pollution = pollution * 1.1
adj_pollution 

# Use NumPy broadcasting to adjust pollution values based on correction factors.
pollution = df['aqi'].to_numpy()
correction_factors = np.array([0.9, 1.0, 1.1])
adjusted_pollution = pollution[:, np.newaxis] * correction_factors

# Calculate percentile-based thresholds for pollution classification.
low, medium, high = np.percentile(df['aqi'], [25, 50, 75])
thresholds = np.percentile(df['aqi'], [25, 50, 75])
thresholds

array([ 87., 103., 121.])

# VISUALIZATION QUESTIONS (Matplotlib + Seaborn)

In [ ]:
import matplotlib.pyplot as plt

 # Plot a line chart showing pollution trend over time.
df['timestamp'] = pd.to_datetime(df['timestamp'])

trend = (
    df.set_index('timestamp')['aqi']
      .resample('D')
      .mean()
)

plt.figure(figsize=(10, 4))
plt.plot(trend.index, trend.values, linewidth=1)
plt.title("pollution trend over time")
plt.xlabel('Date')
plt.ylabel('AQI')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
#Create a bar chart comparing average pollution levels across top 10 cities.
import matplotlib.pyplot as plt

avg_city = (
    df.groupby('city')['aqi']
      .mean()
      .sort_values(ascending=False)
      .head(10))

plt.figure(figsize=(10, 5))
plt.bar(avg_city.index, avg_city.values)
plt.title("Average polution")
plt.xlabel('City')
plt.ylabel('Average AQI')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

In [ ]:
# Plot a histogram to show distribution of pollution values.

import matplotlib.pyplot as plt

plt.figure()
plt.hist(df['aqi'], bins=20, edgecolor = 'black')
plt.xlabel('AQI')
plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

In [ ]:
# Create a boxplot to visualize outliers in pollution data.

import matplotlib.pyplot as plt

plt.figure()
plt.boxplot(df['aqi'])
plt.xlabel('AQI')
plt.ylabel('Pollution Level')
plt.tight_layout()
plt.show()

In [ ]:
# Generate a heatmap showing correlation between pollutants (Seaborn).

import seaborn as sns
import matplotlib.pyplot as plt

pollutants = ['aqi', 'pm25', 'pm10', 'no2', 'so2', 'co', 'o3']
corr = df[pollutants].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, cmap='coolwarm', linewidths=0.5)
plt.tight_layout()
plt.show()

In [ ]:
# Create a scatter plot showing relationship between two pollutants.

import matplotlib.pyplot as plt

plt.figure()
plt.scatter(df['pm25'], df['pm10'])
plt.xlabel('PM2.5')
plt.ylabel('PM10')
plt.tight_layout()
plt.show()